---

- name: VPC | Creating an AWS VPC
  local_action: 
    module: ec2_vpc
    region: "{{ vpc_region }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: { "Name":"{{ vpc_name }}" }
    subnets: "{{ vpc_subnets }}" 
    internet_gateway: yes
    route_tables: "{{ route_tables }}"
  register: vpc



- name: VPC | Write vpc id to file inside the vars directory
  shell: echo "{{ vpc.vpc_id }}" > "{{ vpc_name }}-vpc-info.yml"
  args:
    chdir: aws/vars/



- name: VPC | Write public and private subnets id to files inside the vars directory  
  shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}.yml"
  args:
    chdir: aws/vars/
  with_items: vpc.subnets

  

- name: VPC | Set the public and private subnet id as facts
  set_fact:
    vpc_id: "{{ lookup('file', 'aws/vars/' + vpc_name + '-vpc-info.yml') }}"
    public_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-publicA.yml') }}"
    public_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-publicB.yml') }}"
    private_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-privateA.yml') }}"
    private_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-privateB.yml') }}"



