---

- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - aws/vars/vpc.yml

    - aws/vars/rds.yml

    - aws/vars/ec2_key.yml

    - aws/vars/elb.yml

    - aws/vars/asg_lc.yml

    #- aws/vars/webserver.yml

  tasks: 
    - include: aws/tasks/vpc.yml

    - include: aws/tasks/rds.yml

    - include: aws/tasks/ec2_key.yml

    - include: aws/tasks/elb.yml

    - include: aws/tasks/asg_lc.yml

    #- include: aws/tasks/webserver.yml





     
